// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDHoqi0wRsX1f4c5dLUW5Rm18tLuiOAk',
    appId: '1:694666692847:web:80b095320c63baaa9db31a',
    messagingSenderId: '694666692847',
    projectId: 'disciplinex-bbc12',
    authDomain: 'disciplinex-bbc12.firebaseapp.com',
    storageBucket: 'disciplinex-bbc12.firebasestorage.app',
    measurementId: 'G-SVCJ3H1S9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAglYbACi3zvZFv0z5xswsVDTS9O9YlXlQ',
    appId: '1:694666692847:android:55c3e3f46394db7e9db31a',
    messagingSenderId: '694666692847',
    projectId: 'disciplinex-bbc12',
    storageBucket: 'disciplinex-bbc12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDthhzo1dtgDGNHvbyDlUGskxXw3tv1X3g',
    appId: '1:694666692847:ios:74d8d62e887305089db31a',
    messagingSenderId: '694666692847',
    projectId: 'disciplinex-bbc12',
    storageBucket: 'disciplinex-bbc12.firebasestorage.app',
    iosBundleId: 'com.example.antiProcastination',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDthhzo1dtgDGNHvbyDlUGskxXw3tv1X3g',
    appId: '1:694666692847:ios:74d8d62e887305089db31a',
    messagingSenderId: '694666692847',
    projectId: 'disciplinex-bbc12',
    storageBucket: 'disciplinex-bbc12.firebasestorage.app',
    iosBundleId: 'com.example.antiProcastination',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLDHoqi0wRsX1f4c5dLUW5Rm18tLuiOAk',
    appId: '1:694666692847:web:832a23ca357b6fc69db31a',
    messagingSenderId: '694666692847',
    projectId: 'disciplinex-bbc12',
    authDomain: 'disciplinex-bbc12.firebaseapp.com',
    storageBucket: 'disciplinex-bbc12.firebasestorage.app',
    measurementId: 'G-68V953MMZ1',
  );
}
